config/routes.rb
Rails.application.routes.draw do
  get 'tweet/timeline'

  get 'sessions/index'
  post 'sessions/index'

  root 'home#index'
  get 'home/index'

  #twitter routes
  get '/tweet', to: 'tweet#timeline'
  get 'signout_twitter', to: 'sessions#destroy'
  post '/tweet', to: 'tweet#update', as: 'post_tweet'
  post '/tweet/dm', as: 'dm_tweet'

  #oauth routes
  get '/auth/:provider/callback', to: 'sessions#create'
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    redirect_to tweet_timeline_path if session[:oauth_token]
  end
end

app/controllers/sessions_controller.rb
# coding: utf-8
class SessionsController < ApplicationController
  def index
    if session[:user_name]
      @notice = "#{session[:user_name]}でログインしています。"
    end

    if params.key?(:name) || params.key?(:password)
      user = User.find_by_name(params[:name])
      if user && user.authenticate(params[:password])
        session[:user_name] = params[:name]
      else
        session[:user_name] = nil
      end
    end
  end

  def create
    ## URLがtwitterからのリダイレクトURLの場合、sessionにアクセストークンを格納する。 ##
    ## ↑これセキュリティー上ダメかな。笑 ##
    if (request.path_info == "/auth/twitter/callback")
      auth = request.env["omniauth.auth"]
      session[:oauth_token] = auth.credentials.token
      session[:oauth_token_secret] = auth.credentials.secret
      session[:username] = auth.extra.access_token.params[:screen_name]
      redirect_to "/tweet", :notice => "サインイン！"
    else
      redirect_to root_url
    end
  end

  def destroy
    session[:oauth_token] = nil
    session[:oauth_token_secret] = nil
    redirect_to root_url, :notice => "サインアウト！"
    if (request.path_info == "/signout_twitter")
      session[:username] = nil
    end
  end
end

app/controllers/tweet_controller.rb
# coding: utf-8
class TweetController < ApplicationController
  #helper_method :timeline
  before_action :set_twitter_client

  require 'twitter'

  def timeline
    redirect_to root_url unless session[:oauth_token]
    @tweets = @client.home_timeline(:count => 200)
    @followers = @client.followers
  end

  def update
    @client.update(params[:text])
    flash[:success] = '投稿しました！'
    redirect_to action: :timeline
  end

  def dm
    @client.create_direct_message(params[:scrname], params[:text])
    flash[:success] = 'DMを送りました！'
    redirect_to action: :timeline
  end

  private

  def set_twitter_client
    @client = Twitter::REST::Client.new do |config|
      config.consumer_key        = Rails.application.secrets.twitter_consumer_key
      config.consumer_secret     = Rails.application.secrets.twitter_consumer_secret
      config.access_token        = session[:oauth_token]
      config.access_token_secret = session[:oauth_token_secret]
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tweet_helper.rb
module TweetHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TwitterApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
      <div id="container">
	  <div id="user_nav">
              <% if session[:user_name] %>
		  ようこそ！ <%= session[:user_name] %>
              <% end %>
              <%= link_to "twitterにサインイン", "/auth/twitter" %>
	  </div>
	  <%= yield %>
      </div>
  </body>
</html>

app/views/tweet/_post_tweet.html.erb
<%= form_tag(post_tweet_path) do %>
    <%= label_tag(:text, "投稿") %>
    <%= text_area_tag(:text) %>
    <%= submit_tag("ツイート") %>
<% end %>

<%= form_tag(dm_tweet_path) do %>
    <%= label_tag(:text, "DM") %>
    <%= text_area_tag(:text) %>
    <%= label_tag(:scrname, "DM対象") %>
    <% followers_list = @followers.map(&:name).zip @followers.map(&:screen_name) %>
    <%= select_tag(:scrname, options_for_select(followers_list),
		   include_blank: false) %>
    <%= submit_tag("DMを送る") %>
<% end %>

app/views/tweet/timeline.html.erb
<h1>Tweet#timeline</h1>
<p>Find me in app/views/tweet/timeline.html.erb</p>

<%= flash[:success] %>

<%= render partial: 'post_tweet' %>

<% @tweets.each do |tweet| %>
    <%= tweet.text %><br>
    <% if tweet.media? %>
        <% tweet.media.each do |media| %>
            <%= image_tag(media.media_url_https, width: '320') %>
        <% end %>
	<br>
    <% end %>
    <%= "#{tweet.favorite_count}いいね　#{tweet.retweet_count}リツイート" %><br>

<% end %>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
      <%= form.label :name %>
      <%= form.text_field :name, id: :user_name %>
      <%= form.label :password %>
      <%= form.password_field :password %>
      <%= form.password_field :password_confirmation %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>